import React,{useEffect,useMemo,useState} from "react";
import {createRoot} from "react-dom/client";import {openDB} from "idb";import seed from "./seed.json";import titles from "./allTitles.json";import "./style.css";import {registerSW} from "virtual:pwa-register";registerSW({immediate:true});
type Anime={id:string,title:string,status:string,episodes:number|null,score:number|null,genre:string,studio:string,year:number|null,synopsis:string,image:string};
const dbp=openDB("le-anime",2,{upgrade(db){if(!db.objectStoreNames.contains("anime"))db.createObjectStore("anime",{keyPath:"id"})}});
const slug=(s:string)=>s.toLowerCase().normalize("NFKD").replace(/[^a-z0-9]+/g,"-").replace(/^-|-$/g,"");
async function migrate(){const db=await dbp;let all=await db.getAll("anime") as Anime[];const seedMap=new Map((seed as Anime[]).map(a=>[a.title,a]));const have=new Set(all.map(a=>a.title));let changed=false;const tx=db.transaction("anime","readwrite");for(const title of titles as string[]){if(!have.has(title)){const s=seedMap.get(title);await tx.store.put(s||{id:`sheet-${slug(title)}`,title,status:"",episodes:null,score:null,genre:"",studio:"",year:null,synopsis:"",image:""});changed=true}}await tx.done;return changed?await db.getAll("anime") as Anime[]:all}
async function save(a:Anime){await(await dbp).put("anime",a)}async function del(id:string){await(await dbp).delete("anime",id)}const stars=(n:number|null)=>n?"★".repeat(n):"—";
async function cover(title:string){try{const r=await fetch(`https://api.jikan.moe/v4/anime?q=${encodeURIComponent(title)}&limit=1`);if(!r.ok)return"";const j=await r.json();return j.data?.[0]?.images?.jpg?.large_image_url||j.data?.[0]?.images?.jpg?.image_url||""}catch{return""}}
function App(){const[items,setItems]=useState<Anime[]>([]),[q,setQ]=useState(""),[filter,setFilter]=useState("All"),[selected,setSelected]=useState<Anime|null>(null),[edit,setEdit]=useState<Anime|null>(null),[covering,setCovering]=useState(false),[progress,setProgress]=useState(0);
useEffect(()=>{migrate().then(setItems)},[]);
const shown=useMemo(()=>items.filter(a=>(filter==="All"||a.status===filter)&&(`${a.title} ${a.genre} ${a.studio}`.toLowerCase().includes(q.toLowerCase()))).sort((a,b)=>(b.score||0)-(a.score||0)||a.title.localeCompare(b.title)),[items,q,filter]);
const commit=async(a:Anime)=>{await save(a);setItems(await migrate());setEdit(null);setSelected(a)};const remove=async(a:Anime)=>{await del(a.id);setItems(await migrate());setSelected(null)};
const findCovers=async()=>{setCovering(true);const missing=items.filter(a=>!a.image);let done=0;for(const a of missing){const image=await cover(a.title);if(image){a.image=image;await save(a)}done++;setProgress(Math.round(done/missing.length*100));await new Promise(r=>setTimeout(r,750))}setItems(await migrate());setCovering(false)};
const backup=()=>{const b=new Blob([JSON.stringify(items,null,2)],{type:"application/json"});const u=URL.createObjectURL(b),x=document.createElement("a");x.href=u;x.download="le-anime-backup.json";x.click();URL.revokeObjectURL(u)};const restore=(f:File)=>{const r=new FileReader();r.onload=async()=>{try{const data=JSON.parse(String(r.result)),db=await dbp,tx=db.transaction("anime","readwrite");await tx.store.clear();for(const a of data)await tx.store.put(a);await tx.done;setItems(await migrate())}catch{alert("Invalid backup")}};r.readAsText(f)};
return <main><header><div><div className="eyebrow">MY LIBRARY</div><h1>Lè Anime</h1><p>{items.length} titles · stored on this iPhone</p></div><button className="add" onClick={()=>setEdit({id:crypto.randomUUID(),title:"",status:"Planned",episodes:null,score:null,genre:"",studio:"",year:new Date().getFullYear(),synopsis:"",image:""})}>＋</button></header>
<div className="search"><span>⌕</span><input value={q} onChange={e=>setQ(e.target.value)} placeholder="Search anime, genre, studio…"/></div><nav>{["All","Completed","Paused","Planned"].map(x=><button key={x} className={filter===x?"active":""} onClick={()=>setFilter(x)}>{x}</button>)}</nav>
{items.some(a=>!a.image)&&<button className="save" disabled={covering} onClick={findCovers}>{covering?`Finding cover art… ${progress}%`:"Find cover art"}</button>}
<section className="grid">{shown.map(a=><article key={a.id} onClick={()=>setSelected(a)}><div className="poster">{a.image?<img loading="lazy" src={a.image}/>:<div className="fallback"><b>{a.title.slice(0,1)}</b><span>{a.title}</span></div>}<span className="badge">{a.status||"Uncategorized"}</span></div><h3>{a.title}</h3><div className="rating">{stars(a.score)}</div><small>{a.year||""}{a.episodes?` · ${a.episodes} eps`:""}</small></article>)}</section>
<footer><button onClick={backup}>Export backup</button><label>Import backup<input hidden type="file" accept=".json" onChange={e=>e.target.files?.[0]&&restore(e.target.files[0])}/></label></footer>
{selected&&!edit&&<div className="sheet" onClick={()=>setSelected(null)}><div className="panel" onClick={e=>e.stopPropagation()}><button className="close" onClick={()=>setSelected(null)}>×</button><div className="hero">{selected.image?<img src={selected.image}/>:<div className="heroFallback">{selected.title}</div>}</div><h2>{selected.title}</h2><div className="rating big">{stars(selected.score)}</div><p className="meta">{selected.status||"Uncategorized"} · {selected.year||"—"} · {selected.episodes||"—"} episodes</p><p>{selected.synopsis||"No synopsis yet."}</p><p className="muted">{selected.genre}<br/>{selected.studio}</p><div className="actions"><button onClick={()=>setEdit(selected)}>Edit</button><button className="danger" onClick={()=>remove(selected)}>Delete</button></div></div></div>}
{edit&&<div className="sheet"><form className="panel form" onSubmit={e=>{e.preventDefault();commit(edit)}}><button type="button" className="close" onClick={()=>setEdit(null)}>×</button><h2>{edit.title?"Edit anime":"Add anime"}</h2>{["title","image","genre","studio","synopsis"].map(k=><label key={k}>{k[0].toUpperCase()+k.slice(1)}{k==="synopsis"?<textarea value={(edit as any)[k]} onChange={e=>setEdit({...edit,[k]:e.target.value})}/>:<input required={k==="title"} value={(edit as any)[k]} onChange={e=>setEdit({...edit,[k]:e.target.value})}/>}</label>)}<div className="row"><label>Status<select value={edit.status} onChange={e=>setEdit({...edit,status:e.target.value})}><option value="">Uncategorized</option>{["Completed","Paused","Planned"].map(x=><option key={x}>{x}</option>)}</select></label><label>Score<select value={edit.score??""} onChange={e=>setEdit({...edit,score:e.target.value?+e.target.value:null})}><option value="">—</option>{[1,2,3,4,5].map(x=><option key={x} value={x}>{x} ★</option>)}</select></label></div><div className="row"><label>Episodes<input type="number" value={edit.episodes??""} onChange={e=>setEdit({...edit,episodes:e.target.value?+e.target.value:null})}/></label><label>Year<input type="number" value={edit.year??""} onChange={e=>setEdit({...edit,year:e.target.value?+e.target.value:null})}/></label></div><button className="save">Save</button></form></div>}</main>}
createRoot(document.getElementById("root")!).render(<App/>);