import React,{useEffect,useMemo,useState} from "react";
import {createRoot} from "react-dom/client"; import {openDB} from "idb"; import seed from "./seed.json"; import "./style.css";
import {registerSW} from "virtual:pwa-register"; registerSW({immediate:true});
type Anime={id:string,title:string,status:string,episodes:number|null,score:number|null,genre:string,studio:string,year:number|null,synopsis:string,image:string};
const dbp=openDB("le-anime",1,{upgrade(db){db.createObjectStore("anime",{keyPath:"id"})}});
async function load(){let db=await dbp;let all=await db.getAll("anime");if(!all.length){let tx=db.transaction("anime","readwrite");for(const a of seed as Anime[])await tx.store.put(a);await tx.done;all=await db.getAll("anime")}return all as Anime[]}
async function save(a:Anime){(await dbp).put("anime",a)} async function del(id:string){(await dbp).delete("anime",id)} const stars=(n:number|null)=>n?"★".repeat(n):"—";
function App(){
 const [items,setItems]=useState<Anime[]>([]),[q,setQ]=useState(""),[filter,setFilter]=useState("All"),[selected,setSelected]=useState<Anime|null>(null),[edit,setEdit]=useState<Anime|null>(null);
 useEffect(()=>{load().then(setItems)},[]);
 const shown=useMemo(()=>items.filter(a=>(filter==="All"||a.status===filter)&&(`${a.title} ${a.genre} ${a.studio}`.toLowerCase().includes(q.toLowerCase()))).sort((a,b)=>(b.score||0)-(a.score||0)||a.title.localeCompare(b.title)),[items,q,filter]);
 const commit=async(a:Anime)=>{await save(a);setItems(await load());setEdit(null);setSelected(a)}; const remove=async(a:Anime)=>{await del(a.id);setItems(await load());setSelected(null)};
 const backup=()=>{const b=new Blob([JSON.stringify(items,null,2)],{type:"application/json"});const u=URL.createObjectURL(b);const x=document.createElement("a");x.href=u;x.download="le-anime-backup.json";x.click();URL.revokeObjectURL(u)};
 const restore=(f:File)=>{const r=new FileReader();r.onload=async()=>{try{let data=JSON.parse(String(r.result));let db=await dbp;let tx=db.transaction("anime","readwrite");await tx.store.clear();for(const a of data)await tx.store.put(a);await tx.done;setItems(await load())}catch{alert("Invalid backup")}};r.readAsText(f)};
 return <main><header><div><div className="eyebrow">MY LIBRARY</div><h1>Lè Anime</h1><p>{items.length} titles · stored on this iPhone</p></div><button className="add" onClick={()=>setEdit({id:crypto.randomUUID(),title:"",status:"Planned",episodes:null,score:null,genre:"",studio:"",year:new Date().getFullYear(),synopsis:"",image:""})}>＋</button></header>
 <div className="search"><span>⌕</span><input value={q} onChange={e=>setQ(e.target.value)} placeholder="Search anime, genre, studio…"/></div><nav>{["All","Completed","Paused","Planned"].map(x=><button key={x} className={filter===x?"active":""} onClick={()=>setFilter(x)}>{x}</button>)}</nav>
 <section className="grid">{shown.map(a=><article key={a.id} onClick={()=>setSelected(a)}><div className="poster">{a.image?<img src={a.image}/>:<div className="fallback"><b>{a.title.slice(0,1)}</b><span>{a.title}</span></div>}<span className="badge">{a.status}</span></div><h3>{a.title}</h3><div className="rating">{stars(a.score)}</div><small>{a.year||""}{a.episodes?` · ${a.episodes} eps`:""}</small></article>)}</section>
 <footer><button onClick={backup}>Export backup</button><label>Import backup<input hidden type="file" accept=".json" onChange={e=>e.target.files?.[0]&&restore(e.target.files[0])}/></label></footer>
 {selected&&!edit&&<div className="sheet" onClick={()=>setSelected(null)}><div className="panel" onClick={e=>e.stopPropagation()}><button className="close" onClick={()=>setSelected(null)}>×</button><div className="hero">{selected.image?<img src={selected.image}/>:<div className="heroFallback">{selected.title}</div>}</div><h2>{selected.title}</h2><div className="rating big">{stars(selected.score)}</div><p className="meta">{selected.status} · {selected.year||"—"} · {selected.episodes||"—"} episodes</p><p>{selected.synopsis||"No synopsis yet."}</p><p className="muted">{selected.genre}<br/>{selected.studio}</p><div className="actions"><button onClick={()=>setEdit(selected)}>Edit</button><button className="danger" onClick={()=>remove(selected)}>Delete</button></div></div></div>}
 {edit&&<div className="sheet"><form className="panel form" onSubmit={e=>{e.preventDefault();commit(edit)}}><button type="button" className="close" onClick={()=>setEdit(null)}>×</button><h2>{edit.title?"Edit anime":"Add anime"}</h2>{["title","image","genre","studio","synopsis"].map(k=><label key={k}>{k[0].toUpperCase()+k.slice(1)}{k==="synopsis"?<textarea value={(edit as any)[k]} onChange={e=>setEdit({...edit,[k]:e.target.value})}/>:<input required={k==="title"} value={(edit as any)[k]} onChange={e=>setEdit({...edit,[k]:e.target.value})}/>}</label>)}<div className="row"><label>Status<select value={edit.status} onChange={e=>setEdit({...edit,status:e.target.value})}>{["Completed","Paused","Planned"].map(x=><option key={x}>{x}</option>)}</select></label><label>Score<select value={edit.score??""} onChange={e=>setEdit({...edit,score:e.target.value?+e.target.value:null})}><option value="">—</option>{[1,2,3,4,5].map(x=><option key={x} value={x}>{x} ★</option>)}</select></label></div><div className="row"><label>Episodes<input type="number" value={edit.episodes??""} onChange={e=>setEdit({...edit,episodes:e.target.value?+e.target.value:null})}/></label><label>Year<input type="number" value={edit.year??""} onChange={e=>setEdit({...edit,year:e.target.value?+e.target.value:null})}/></label></div><button className="save">Save</button></form></div>}</main>
} createRoot(document.getElementById("root")!).render(<App/>);